name: lktrans
description: LKTrans - frontend Flutter
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  shared_preferences: ^2.1.1
  dotted_line: ^3.0.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_lk.png
    - assets/images/bus_sample.jpg
